### ISSUE TITLE
Provide alternative HudPlayerHealth.res with a health cross

### ISSUE THREAD

**Issue by nTraum** [omp/tf2hud#5]
Hi,

first of all, thanks for the great HUD. I love it and I also love having it hosted on GitHub. :)

I'd like to ask you to provide a HudPlayerHealth.res with a health cross enabled. Some people (like me)  favour this insteaf of plain numbers.

Keep up the good work.

Thanks!

**Comment by Felix243** [comment]
well the descusion is over now but what should I set my xpos and ypos too?

**Comment by IniZio** [comment]
Its stated in second comment already.
